apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  labels:
    run: wil-playground
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: wil-playground
