apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  labels:
    run: wil-playground
spec:
  type: NodePort
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
    nodePort: 30080
  selector:
    app: wil-playground
